export const RESET_ALL_2_INITIAL_STATE = 'RESET_2_INITIAL_STATE';
export const HISTORY_TASK_ALL = 'HISTORY_TASK_ALL'
export const LESSON_TASK_ALL = 'LESSON_TASK_ALL'
export const LOGIN_TASK_ALL = 'LOGIN_TASK_ALL'
